language: php
php:
- 7.3
before_script:
- cp .env.travis .env
- composer self-update
- composer install --no-interaction
- php artisan key:generate
- php artisan migrate
- npm install
- npm run prod
before_install:
- openssl aes-256-cbc -K $encrypted_3c96886c4e51_key -iv $encrypted_3c96886c4e51_iv -in deploy_key.pub.enc -out deploy_key.pub -d
- chmod 600 deploy_key.pub
- eval "$(ssh-agent -s)"
- ssh-add deploy_key.pub
- mysql -e 'CREATE DATABASE `laravel-url-shortener-testing`;'
services:
- mysql
script:
- vendor/bin/phpunit
after_success:
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add deploy_key.pub
- ssh -i deploy_key.pub root@138.197.164.139 pwd
